### ISSUE TITLE
CN translate needs to update!

### ISSUE THREAD

**Issue by DoctorKoKoDaYo** [offyerrocker/PD2-TacticalLeaning#1]
HERE is latest translate made by myself(MY MWS link :https://modworkshop.net/user/44255)
{
	"taclean_title" : "Tactical Leaning模组设置",
	"taclean_togglelean_title" : "切换探头",
	"taclean_togglelean_desc" : "如果启用，只需按下键位即可以持续探头；否则，必须按住键位以持续探头。",
	"taclean_keybind_right_title" : "向右探头",
	"taclean_keybind_right_desc" : "绑定一个键位应用于向右探头",
	"taclean_keybind_left_title" : "向左探头",
	"taclean_keybind_left_desc" : "绑定一个键位应用于向左探头",
	"taclean_slider_distance_title" : "探头距离",
	"taclean_slider_distance_desc" : "改变探头距离",
	"taclean_slider_angle_title" : "探头角度",
	"taclean_slider_angle_desc" : "改变探头角度"
    "clean_togglecontrollermode_title" : "控制器模式",
	"taclean_togglecontrollermode_desc" : "在瞄准时按下控制器的 \"冲刺\" 或 \"近战\"键位时将相应的向左/向右探头",
	"taclean_toggle_autounlean_title" : "控制器:自动取消探头",
	"taclean_toggle_autounlean_desc" : "在您使用控制器时，退出瞄准状态会自动取消探头",
	"hud_taclean_state_blocked_downed" : "倒地时禁用探头！"
	"hud_taclean_state_blocked_generic" : "此处无法探头！",
	"menu_taclean_missing_htk_prompt_title" : "缺少依赖模组：HoldTheKey！",
	"menu_taclean_missing_htk_prompt_desc" : "您尚未安装HoldTheKey模组,或者您没有正确安装它\n缺少该模组会导致游戏崩溃或本模组失效！\nHoldTheKey是Tactical Leaning模组的依赖模组！"
	}

**Comment by offyerrocker** [comment]
Thanks for your contribution- it has been added to the latest update v3.1. I apologize for the delay, as I have been busy working on this update (among other things).
